pipeline {
    // Run on an agent where we want to use Go
    // agent { docker { image 'golang:1.20-alpine' } }
    agent { label 'codeclarity' }

    environment {
        DOCKERHUB_CREDENTIALS=credentials('dockerhub')
    }
    stages {
        stage('Login') {

			steps {
				sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
			}
		}
        stage('Build') {
            steps {
                sh 'docker system prune -af'
                sh 'git submodule update --init --recursive'
                sh 'git fetch --tags --force'
                script {
                    def project =readJSON file: 'config.json'
                    env.Version = project.version
                    env.Name = project.image_name
                    sh 'echo $Version'
                    env.Tag = "${Name}:${Version.substring(1)}"
                    sh 'echo $Tag'
                    sh "sh .cloud/jenkins/check_version.sh ${Version}"
                    withCredentials(
                        [
                            file(credentialsId: 'netrc', variable: 'netrc'),
                        ]
                    ) {
                        writeFile file: '.cloud/docker/config/.netrc', text: readFile(netrc)
                    }
                }
            }
        }
        // stage('Test') {
        //     steps {
        //         // Output will be something like "go version go1.19 darwin/arm64"
        //         sh 'make'
        //     }
        // }
        stage('Deploy') {
            steps {
                // Output will be something like "go version go1.19 darwin/arm64"
                // sh 'make push'
                sh 'docker buildx rm plugin || true'
                sh 'docker buildx create --name plugin --use --bootstrap'
                sh 'docker buildx build -f .cloud/docker/Dockerfile --platform linux/amd64,linux/arm64 --target plugin --tag $Name:latest --tag $Tag --push .'
            }
        }
    }
}