services:
  plugin-scanpy:
    # For dev we keep the golang container and install devtools
    build:
      target: plugin-debug
    image: parithera/scanpy-debug:latest
    ports:
      - 40000:40000
